authzed/docs

docs/spicedb/selecting-a-datastore.md

Related to #21 
- `--datastore-kind` -> `--datastore-engine`
- `--datastore-engine=memdb` -> `--datastore-engine=memory`

Update parameter to select a spicdb datastore

---

docs/spicedb/selecting-a-datastore.md

I reworked this doc and included the missing info from #27.

Add migrations section to datastore reference

---

docs/guides/schema.md

This file is already relative to `guides`, which leads to the following URL (https://docs.authzed.com/guides/guides/first-app) when navigating from https://docs.authzed.com/guides/schema#get-started-for-real.

Fix link to first-app guide

---

docs/guides/first-app.mdx

The CLI call was broken because the names didn't line up. It seems to be fine for the other language examples.

Fix CLI call for creating and checking relationships

---

docs/guides/first-app.mdx

I noticed some syntax errors when attempting to use the Ruby code samples for the first app. This PR fixes those issues.

fix: ruby code samples in first-app.mdx

---

docs/spicedb/installing.md

This PR:
The current installation command does not work directly because it assumes that Authzed's tap has already been installed.

docs: fix homebrew installation command

---

docs/spicedb/selecting-a-datastore.md

This change moves datastore-spanner-credentials to the optional parameters section and describes how to use application default credentials by omitting a credential path.
My local markdown formatter also updated the formatting of tables in this file (happy to revert that part).
Updates https://github.com/authzed/spicedb/issues/665

document use of application default credentials with spanner

---

docs/guides/first-app.mdx

As-is, the first Go example in the Protecting your first app doesn't run because of an unused import and an unused variable.

first-app: Make first Go example compile

---

docs/guides/defining-a-subject-type.md

I'm pretty sure
```
definition service {
token: token
}
```
is supposed to be 
```
definition service {
relation token: token
}
```
but let me know if I'm misunderstanding something. Thanks!

Fix relation in defining-a-subject-type.md

---

docs/reference/api.md

The documentation surrounding the HTTP API is a little misleading. When I read the documentation, I came to the conclusion that I needed to setup my own gRPC Gateway service. Only after asking a question in the Discord channel did I learn about the article that explains how to enable the HTTP API.

Link to article explaining how to enable HTTP API

---

docs/guides/first-app.mdx

With go modules we need to run a few extra steps.

Improve tutorial for go.

---

docs/reference/api.md
docs/reference/clients.md
docs/spicedb/feature-overview.md
sidebars.js

Also refreshed the SpiceDB postman workspace with openapi generated docs:
https://www.postman.com/authzed/workspace/c1b9ce6b-7482-4363-8a09-71521355b6d9/api/c7764854-8b04-4441-8360-a6b2f1d52064

Replace swaggerhub with postman link

---

docs/reference/caveats.md

The `CheckPermissionRequest` example is incorrect — rather than specifying the `Relation` field, the example should specify the `Permission` field.

fix CheckPermissionRequest schema in caveats.md

---

docs/spicedb/installing.md

According to [SpiceDB Issue 1072](https://github.com/authzed/spicedb/issues/1072), `--rm ` in the shared command for a Docker based installation is causing persistence issues with the SpiceDB docker container.

Addresses SpiceDB issue 1072

---

docusaurus.config.js

This change reads the baseURL from the environment.
This fixes a bug where previews need a value of `/` but production uses `/docs/`.

read baseURL from environment

---

docs/spicedb/selecting-a-datastore.md

Just a small change, but I hope it helps sombody running into issues trying to follow the mysql datastore examples
- The MySQL example does not work with the go-mysql driver that SpiceDB ships with. The format is actually `username:password@(host:port)/schema`. I also replaced the word `mysql` with `username` to clarify that it's not the protocol but the username.
- `sslmode` is not a valid parameter for the mysql driver

Clarify MySQL examples in selecting-a-datastore.md

---

docs/guides/validation-and-testing.md

This step is necessary to successfully use the zed validate github action.

Adding actions/checkout@v3 to github action docs

---

vercel.json

Overriding the automatically set header value for proxied requests from authzed.com

Override robots header for proxied requests

---

docs/guides/first-app.mdx

Using `grpcutil.WithInsecureBearerToken` seems to require also using the `grpc.WithTransportCredentials(insecure.NewCredentials())` option.

docs/guides: Fix example code: Protecting Your First App

---

docusaurus.config.js
package.json

Replacing deprecated UA with GA4.
Updated deployment with the new env var.

Replace deprecated Google Analytics property with GA4

---

docs/guides/first-app.mdx

Guide at: https://authzed.com/docs/guides/first-app in section **Defining and Applying a Schema** generates incorrect Python example when using `I have an [Authzed permissions system](https://app.authzed.com/) created` option.
Before:
```
client = Client(
"grpc.authzed.com:443",
bearer_token_credentials("t_your_token_here_1234567deadbeef"),bearer_token_credentials("t_your_token_here_1234567deadbeef"),
)
```
(`bearer_token_credentials` gets repeated twice).
This PR fixes this to generate a version of code that works:
```
client = Client(
"grpc.authzed.com:443",
bearer_token_credentials("t_your_token_here_1234567deadbeef"),
)
```

Fixes initial Python Client connect code in "Defining and Applying a Schema"

---

docs/spicedb/installing.md

Noticed brew install command did not install zed

Update installing.md documentation with correct brew tap for zed cli

---

docs/spicedb/selecting-a-datastore.md

It's actually 1.25 hours, not 1.5

correct GC TTL in CRDB Serverless

---

README.md
docs/guides/debugging.md
docs/guides/defining-a-subject-type.md
docs/guides/first-app.mdx
docs/guides/schema.md
docs/guides/writing-relationships.md
docs/overview.md
docs/reference/caveats.md
docs/reference/schema-lang.md
docs/spicedb-dedicated/networking/aws.md
docs/spicedb-dedicated/overview.md
docs/spicedb-serverless/overview.md
docs/spicedb/configuring-dispatch.md
docs/spicedb/enabling-watch-api.md
docs/spicedb/installing.md
docs/spicedb/operator.md
docs/spicedb/selecting-a-datastore.md
docs/spicedb/updating.md

- Document pnpm in README
- Fix relative path links to use file paths
Using file path in links takes advantage of broken link detection at build time and incorporates base path settings. https://docusaurus.io/docs/markdown-features/links

Fix relative doc links

---

docs/spicedb-serverless/overview.md

The endpoint for HTTP Gateway
in SpiceDB serverless isn't properly
documented. Additionally a postman
collection exists that can help onboard
folks but is also undiscoverable.

document SpiceDB Serverless HTTP Gateway

---

.github/workflows/link-checker-full.yaml
.github/workflows/link-checker.yaml
linkcheck-skip.txt
pages/authzed/guides/picking-a-product.mdx
pages/authzed/guides/setting-up-private-networking.mdx
pages/spicedb/concepts/caveats.mdx
pages/spicedb/concepts/datastore-migrations.mdx
pages/spicedb/concepts/datastores.mdx
pages/spicedb/concepts/dispatch.mdx
pages/spicedb/getting-started/discovering-spicedb.mdx
pages/spicedb/getting-started/installing-spicedb.mdx
pages/spicedb/getting-started/protecting-a-blog.mdx
pages/spicedb/links/_meta.json
pages/spicedb/modeling/representing-users.mdx
pages/spicedb/ops/deploying-spicedb-operator.mdx
pages/spicedb/ops/load-testing.mdx
pages/spicedb/ops/observability.mdx
theme.config.tsx

- **Re-enable page edit link**
- **Fix internal links**
- **Fix external links**
- **Replace lychee with linkcheck**

Replace lychee with linkcheck

---

linkcheck-skip.txt
next.config.mjs
vercel.json

- **Redirect root path for preview deployments**
- **Add to linkcheck skip list**

Fix link check for main branch

---

pages/spicedb/concepts/zanzibar.mdx

Resolves Issue #223 
1. Updated heading for the example in the file `pages/spicedb/concepts/zanzibar.mdx`

fix: example heading under new enemy problem section

---

pages/spicedb/concepts/caveats.mdx

Caveat definition with a cidr like this throws an error in the playground: "evaluation error for caveat has_valid_ip: invalid CIDR string: `10.20.30.0`"
Needs to have the /24 appendage

Fix caveats.mdx CIDR definition

---

README.md
pages/spicedb/concepts/commands.mdx
pages/spicedb/concepts/datastores.mdx

this PR adds documentation around MySQL and Postgres replica support in SpiceDB

add documentation around MySQL and Postgres replica support in SpiceDB

---

pages/spicedb/concepts/operator.mdx

This came up on discord: https://discord.com/channels/844600078504951838/844600078948630559/1294038324285280388
We had documentation [in the release notes](https://github.com/authzed/spicedb-operator/releases/tag/v1.2.0) but not in the documentation, so this brings it in.
Add section on customization of operator-managed objects
Review

Add documentation of operator patches

---

pages/spicedb/concepts/datastores.mdx

We've gotten a couple of questions in discord around this recently, and it'd help to be able to point folks at documentation.
* Reword item in the list of things to think about
* Add section on MVCC and `spicedb datastore repair`
Review

Add section to postgres datastore about MVCC and datastore repair

---

pages/spicedb/ops/load-testing.mdx

Adding thumper documentation before we release thumper more broadly
Add more documentation around thumper
Review

Expand thumper documentation

---

pages/authzed/concepts/authzed-materialize.mdx

I think a single `select` comes off as simpler to grok right now. 
The motivation here was that when I was grafting materialize onto an existing project for a demo, I found the ORM that project used made it much easier to build non-union queries. 
My only concern with this example is that non-inner joins are much less common and might be confusing in their own right - might be worth coming back to this and expanding on the reason (in this case it's because we don't want to discard rows from the join if they don't have a `set_to_set` match, since they might have a "direct" `member_to_set` match.)

Update materialize doc with simpler SQL

---

pages/spicedb/getting-started/install/debian.mdx

Fixes #293 
I went to use these instructions to get a local binary of `spicedb` so that I could test something with the VSCode extension. I noticed that our instructions still use `apt-key add`, which [has been deprecated](https://medium.com/@glegoux/ubuntu-22-04-jammy-jellyfish-apt-key-is-deprecated-2dbbee8aec84). This updates to the new method, which cribs from the [kubernetes directions](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#install-using-native-package-management).
* Update documentation around debian installation
Review.

Update debian install instructions

---

pages/authzed/guides/setting-up-private-networking.mdx

AWS Console has changed its options when creating new VPC Endpoints.  Updated to correct option here.

Update AWS private networking instructions

---

pages/authzed/concepts/restricted-api-access.mdx

the documentation incorrectly described how to
generate a token, suggesting the caller should
provide a value like <prefix>_<hash>, when in
fact it should be <prefix>_<secret>
It also clarifies the flags needed for enable
restricted api access with static configuration.

adjust restricted api access token generation

---

pages/spicedb/modeling/validation-testing-debugging.mdx

We added new functionality to `zed validate` with the `schemaFile` key and the ability to validate multiple files at the same time. This both elaborates on existing documentation and adds documentation of those new features.
Update documentation
Review

Update zed validate docs

---

pages/spicedb/concepts/datastore-migrations.mdx

This came up in a discord conversation and I was uncertain of the behavior. I went and asked around and figured I'd document here.
* Add section on DB migration compatibility
Review

Add notes on DB migration compatibility

---

pages/spicedb/modeling/composable-schemas.mdx

We got a question from a user about this - it wasn't clear from the docs whether a definition could contain multiple partial references.
* Add clarification to docs around multiple partial references
Review.

Clarify partial reference behavior

---

pages/spicedb/modeling/composable-schemas.mdx

The composable schema syntax has some meaningful differences from the writeable schema language, and they may be a breaking change for some users.
* Add section on breaking changes
Review.

Add section on breaking schema changes

---

pages/spicedb/concepts/datastores.mdx

updates datastore-conn-pool-* flags, corrects formatting of datastore-read-replica-* flags, fix spelling mistake

datastore.mdx flags update

---

.gitignore
components/nextra/Search.tsx
components/scripts.tsx
package.json
pages/_app.mdx
pnpm-lock.yaml

- **Add script configuration**
- **Add analytics**

Scripts update

---

pages/spicedb/concepts/reflection-apis.mdx

remove experimental references from reflection api docs

remove experimental references from reflection api docs.mdx

---

pages/spicedb/modeling/validation-testing-debugging.mdx

A user on discord pointed out that the example file doesn't work as written. This is because we were using a [folding block scalar](https://yaml-multiline.info/#block-scalars) instead of a literal, which meant that it was turning newlines into spaces and causing the relation parsing to fail. We need to preserve newlines, which the literal does.
* Use literal block scalar
Review. Copy out this block and run `zed validate` against it and see that it succeeds.

Use literal block format for example validation

---

pages/authzed/concepts/authzed-materialize.mdx

My goal was to make the text flow better. So I structured it like so:
- what it is
- what it is good for
- limitations

rewrite intro to materialize

---

pages/spicedb/getting-started/install/debian.mdx
pages/spicedb/getting-started/installing-zed.mdx

Fixes #345 
A user pointed out in #345 that the zed installation documentation is outdated, and we've already made this change in the SpiceDB install docs.
It'd probably be better to reorganize the docs to centralize the "set up debian sources" documentation, but I'm going to leave that for later.
* Make zed installation documentation mirror SpiceDB's
Review.

Update zed installation docs to match spicedb

---

pages/authzed/guides/picking-a-product.mdx

Fix discord invitation link to use https://authzed.com/discord specified on https://authzed.com/products/authzed-support

Fix discord invitation link

---

components/swagger.tsx
globals.css
package.json
pages/authzed/api/_meta.json
pages/authzed/api/http-api.mdx
pages/spicedb/api/_meta.json
pages/spicedb/api/http-api.mdx
pnpm-lock.yaml

add swagger doc

---

pages/authzed/concepts/restricted-api-access.mdx

This tripped a user up recently; it'd be good to have it documented somewhere.
I also reorganized the documentation a bit, moving the CEL documentation up a level and down the page.
* Add documentation for perms required for zed backup/restore
* Reorganize existing documentation
Review. See that you like the look of the page.

Document APIs required for zed backup/restore
