package.json
yarn.lock

Signed-off-by: Sam Kim <sam@authzed.com>

Nov dependabot updates

---

docs/reference/api.md

This is not a fully fledged document on how to configure this functionality for SpiceDB, but rather an overview for those learning about the capabilities of the API.

api: add section on gateway

---

docusaurus.config.js
package.json
src/components/AmplitudeClient.tsx
src/components/Feedback.tsx
src/css/custom.css
src/theme/DocItemFooter.tsx
src/theme/Root.tsx
yarn.lock

* Add amplitude config and client
* Add Yes/No feedback component
* Add question submit component
Screenshots

Add Amplitude client and custom feedback component

---

src/components/ClientSideOnly.tsx
src/theme/Root.tsx

Fixes build issue: 
```
ReferenceError: navigator is not defined
```

Add client side only component

---

docs/guides/first-app.md

Signed-off-by: Burak Sekili <buraksekili@gmail.com>
Hi, I was following [Protecting Your First App](https://docs.authzed.com/guides/first-app) documentation to get started with SpiceDB. While trying the examples on my local setup, I realized minor issues (i.e, missing commas) in Go codes related to permission operations code pieces.
This PR updates [Protecting Your First App](https://docs.authzed.com/guides/first-app) document to resolve issues described above.

Update Go codes for first-app doc

---

docs/reference/schema-lang.md

Add a "Common Patterns" section with examples

Add schema patterns to schema lang page

---

docs/reference/glossary.md
docs/reference/schema-lang.md

See https://github.com/authzed/spicedb/pull/336

Add documentation for wildcard (public) support

---

docs/guides/first-app.mdx
docusaurus.config.js
package.json
src/components/SampleConfigProvider.tsx
src/components/debouncer.tsx
src/css/custom.css
webpack-fallbacks-plugin.js
yarn.lock

- Add a warning around use of zedtokens or consistency
- Implement a handler for adjusting code samples based on entered endpoint, tenant, token etc

Improve the "protecting your first app" guide

---

src/css/custom.css

Restyle announcement bar to match authzed.com

---

docs/reference/glossary.md

Some of the markdown also auto-reformatted

Update prefix description to make it more accurate

---

docs/guides/schema.md

Fixes a small typo in schema.md

Fix typo in schema.md

---

README.md
docs/guides/debugging.md
docs/guides/schema.md
docs/overview.md
docs/products/serverless.md
docs/reference/glossary.md
docs/spicedb/feature-overview.md
docusaurus.config.js
vercel.json

- Update baseUrl
- Make images baseUrl aware

Update site URl

---

docs/guides/schema.md
docs/reference/schema-lang.md

Clarify use and requirement of prefixes in schema

---

docs/reference/caveats.md
docs/reference/schema-lang.md

Removes the experimental flag and adds a reference to the schema language doc

Update documentation for caveats

---

v1.20.0+enterprise.v1.md

Update documentation with release notes for SpiceDB Enterprise v1.20.0+enterprise.v1

---

docs/guides/first-app.mdx

fixes https://github.com/authzed/docs/issues/77
some bits were missing that required
that forced newcomers to figure out
how to wire things up. This should be
a working self-contained go example

updates go example to be self-contained

---

docs/spicedb-enterprise/v1.21.0+enterprise.v1.md

Update documentation with release notes for SpiceDB Enterprise v1.21.0+enterprise.v1

---

docs/spicedb-enterprise/v1.22.2+enterprise.v1.md

Update documentation with release notes for SpiceDB Enterprise v1.22.2+enterprise.v1

---

docs/spicedb-enterprise/v1.23.0+enterprise.v1.md

Update documentation with release notes for SpiceDB Enterprise v1.23.0+enterprise.v1

---

docs/spicedb-enterprise/v1.23.1+enterprise.v1.md

Update documentation with release notes for SpiceDB Enterprise v1.23.1+enterprise.v1

---

docs/spicedb-enterprise/v1.24.0+enterprise.v1.md

Update documentation with release notes for SpiceDB Enterprise v1.24.0+enterprise.v1

---

docs/spicedb-enterprise/v1.25.0+enterprise.v1.md

Update documentation with release notes for SpiceDB Enterprise v1.25.0+enterprise.v1

---

docs/spicedb/installing.md

Depends on https://github.com/jzelinskie/cobrautil/pull/48

Document configuration via .env files

---

docusaurus.config.js
sidebars.js
src/css/custom.css

Adding links to schedule a call for further questions or support.

Add links to talk to an expert

---

docs/spicedb-enterprise-releases/v1.26.0+enterprise.v1.md

Update documentation with release notes for SpiceDB Enterprise v1.26.0+enterprise.v1

---

docs/spicedb-enterprise-releases/v1.27.0+enterprise.v1.md

Update documentation with release notes for SpiceDB Enterprise v1.27.0+enterprise.v1

---

docs/guides/schema.md
docs/overview.md
docs/spicedb/deploy-on-eks.md

This PR relates to one of the current errors discovered by SEMRush. This will hopefully fix the broken links issue.

SEMRush broken links fix

---

docs/spicedb-enterprise-releases/v1.28.0+enterprise.v1.md

Update documentation with release notes for SpiceDB Enterprise v1.28.0+enterprise.v1

---

docs/spicedb-enterprise/fgam.md

the docs described incorrectly how to
generate the tokens

fgam: fix docs around token generation

---

docs/spicedb-enterprise-releases/v1.29.0+enterprise.v1.md

Update documentation with release notes for SpiceDB Enterprise v1.29.0+enterprise.v1

---

vercel.json

- Move redirects
- Use base dir in redirects
- Move redirects out of docs

Move redirects out of docs

---

next.config.mjs

- Move redirects
- Use base dir in redirects
- Move redirects out of docs
- Set assetPrefix for production deploys
- Use baseDir in assetPrefix

Use baseDir in assetPrefix

---

components/footer.tsx
components/layout.tsx
pages/_app.mdx
pages/_meta.json
pages/index.mdx
pages/spicedb/getting-started/discovering-spicedb.mdx

- Add Inter font
- Footer styling
- Add root index page config
- Update product card link

Nextra styling and config updates

---

components/banner.tsx
theme.config.tsx

Add initial banner component and section specific messages

Add banner component

---

.github/workflows/link-checker.yaml

Uses lychee https://github.com/lycheeverse/lychee

Add link checker workflow

---

.github/workflows/link-checker-full.yaml

- **linkcheck: Ignore anchor warnings**

linkcheck: Ignore missing anchor warnings

---

.gitignore
.npmrc
next-sitemap.config.js
package.json
pnpm-lock.yaml
theme.config.tsx

Use next-sitemap to generate sitemaps during postbuild.

Add sitemap generation

---

pages/authzed/concepts/audit-logging.mdx

Adds additional details to the audit logging extender docs.

Update audit logging docs

---

pages/spicedb/concepts/caveats.mdx
pages/spicedb/concepts/relationships.mdx
pages/spicedb/modeling/developing-a-schema.mdx

See https://nextra.site/docs/guide/syntax-highlighting#filenames-and-titles

Fix code block titles

---

pages/spicedb/modeling/protecting-a-list-endpoint.mdx

Some version of this question pops up pretty regularly on Discord. It'd be good to have documentation that we can point users to, and this could potentially be something that users discover before getting to where they ask the question.
Add the docs
Lemme know what you think

Add doc page for protecting a list endpoint

---

pages/spicedb/ops/observability.mdx

Fixes https://github.com/authzed/docs/issues/233

Fix video embed on observability page

---

pages/spicedb/modeling/_meta.json
pages/spicedb/modeling/migrating-schema.mdx

Fixes https://github.com/authzed/spicedb/issues/895

Add doc on schema updates and migrations

---

pages/spicedb/modeling/_meta.json
pages/spicedb/modeling/access-control-audit.mdx

Built on top of https://github.com/authzed/docs/pull/244

add docs for access control audit

---

pages/spicedb/getting-started/install/windows.mdx

Fix typo in windows docs

---

.pre-commit-config.yaml
pages/spicedb/concepts/consistency.mdx

Fixes #247 
See #247 
Add line for recommended storage
Review

Add documentation for fixed-width columns

---

pages/spicedb/getting-started/_meta.json
pages/spicedb/getting-started/client-libraries.mdx
pages/spicedb/getting-started/faq.mdx

Supersedes #201 
An elaboration of the documentation provided in #201 that includes documentation of the openAPI specs.
* Copy in changes from #201
* Add openAPI documentation
Review.

Add additional client documentation

---

pages/spicedb/concepts/datastores.mdx

Adding @josephschorr's relationship integrity docs

Adding relationship integrity docs.mdx

---

package.json
pages/_app.mdx
pnpm-lock.yaml

We have this on our website and the docs are just as important perf-wise!

*: add vercel performance insights

---

pages/spicedb/getting-started/protecting-a-blog.mdx

Fixes #276 
This was called out by a Discord user. We make a reference to a "running" instance, but for a user who is first encountering our system that may not be entirely self-evident.
* Add code block with example SpiceDB invocations
Review.

Add a code block with example usage of spicedb

---

pages/spicedb/concepts/expiring-relationships.mdx

The PR auto-merged and I didn't have the change to address comments
FYI @reify-tanner-stirrat

follow ups to document expiring relationships

---

pages/spicedb/modeling/_meta.json
pages/spicedb/modeling/composable-schemas.mdx
pages/spicedb/modeling/migrating-schema.mdx
public/authzed.tmLanguage.json

Part of getting composable schemas out the door.
* Add documentation of preview feature
* Update syntax highlighting to support partials and imports
Review. See the rendered stuff and see that it looks good

Add composable schema docs

---

pages/authzed/links/_meta.json
pages/spicedb/getting-started/_meta.json
pages/spicedb/getting-started/install/_meta.json
pages/spicedb/getting-started/install/eks.mdx
pages/spicedb/getting-started/install/kubernetes.mdx
pages/spicedb/links/_meta.json
theme.config.tsx

- adds some links to the navbar
- adjusts navbar to be collapsed by default
- opens some links in a new window
- minor tweak on eks title / intro

adjust navbar collapse and links

---

pages/spicedb/concepts/consistency.mdx

Adds consistency blog post to further reading section and moves the central zed tokens post to the top

Adds consistency blog post to further reading.mdx

---

pages/spicedb/modeling/composable-schemas.mdx

Structure the page like so:
- why we did this
- how it works
- details on new syntax

reorganize composable schemas

---

pages/spicedb/links/_meta.json

In addition to #351, there was also this site, so we're fixing it.
* Update discord link
Review.

Fix broken discord link

---

pages/spicedb/getting-started/protecting-a-blog.mdx

- **updated quickstart guide**
Updated the quickstart guide to add AuthZed Cloud
`pnpm run dev`

Updated Quickstart Guide
